name: Build Vue
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.20.2"
      - run: |
          node --version
          npm install
          npm run build
          cd dist
          ln -s index.html 404.html
          git config --global user.email "CI@example.com"
          git config --global user.name "CI"
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://sloanelauren:${{ secrets.GITHUB_TOKEN }}@github.com/sloanelauren/MyLittleLibrary.git master:gh-pages
        shell: bash